services:
  web:
    build: .
    ports:
      - "5001:8080"
    volumes:
      - .:/app
      - uploads_data:/app/app/static/uploads
      - ./firebase-auth.json:/app/firebase-auth.json
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:taiuong@35.238.163.196:5432/ds_reading_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && python run"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wsunicorn
      - POSTGRES_DB=ds_reading_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  uploads_data: