services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - ./uploads:/app/app/static/uploads
      - ./firebase-auth.json:/app/firebase-auth.json
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:wsunicorn@db:5432/ds_reading_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
# db-docker
    command: >
      sh -c "sleep 10 && flask run --host=0.0.0.0"
  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wsunicorn
      - POSTGRES_DB=ds_reading_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  #dung docker
  postgres_data:
  uploads_data:
